const PopupName = {
  EVENT_SHOW_POPUP: "EVENT_SHOW_POPUP",
  DEMO_POPUP: "DEMO_POPUP",
  POPUP_SUCCESS: "POPUP_SUCCESS",
  POPUP_fAIL: "POPUP_FAIL",
  POPUP_CONFIRM: "POPUP_CONFIRM",
  POPUP_ADD_CUSTOMER: "POPUP_ADD_CUSTOMER",
  POPUP_RETURN_GOODS: "POPUP_RETURN_GOODS",
  POPUP_PAYMENT: "POPUP_PAYMENT",
  POPUP_REPORT_SALES_ENDDAY: "POPUP_REPORT_SALES_ENDDAY",
  POPUP_PRODUCT_DETAIL: "POPUP_PRODUCT_DETAIL",
  POPUP_PAYMENT_ONLINE: "POPUP_PAYMENT_ONLINE",
  POPUP_CANCELED_ORDER: "POPUP_CANCELED_ORDER",
  POPUP_DELIVERY_INFOR: "POPUP_DELIVERY_INFOR",
  CHOOSE_GROUD_ASSET: "CHOOSE_GROUD_ASSET",
  NOTE_POPUP: "NOTE_POPUP",
  EVENT_SHOW_POPUP_ADD_CUSTOMER: "EVENT_SHOW_POPUP_ADD_CUSTOMER",
};

export default PopupName;
